version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: db-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${EMAIL_ADMIN}
      PGADMIN_DEFAULT_PASSWORD: ${PASSWORD_ADMIN}
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  pgdata:
